name: Upload Project to GitHub
on:
  push:
    branches:
      - master
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: project
          path: build/
