
















name: Android CI

on: [push, pull_request]

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Setup Java JDK

      uses: actions/setup-java@v2

      with:

        java-version: '11'

        distribution: 'adopt'

    - name: Setup Node.js

    - uses: actions/setup-node@v2.4.1

      with:

        node-version: 16

    - name: Install Dependencies

      run: |

        npm ci

        npx jetify

    - name: Build Android Release

      run: |

        chmod +x ./android/gradlew

        cd android && ./gradlew assembleRelease
        
